/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yunsoft;

import com.yunsoft.netutil.*;

public class App {

    public static void main(String[] args) {
        NetworkUtil netUtil = new NetworkUtil();
        System.out.println("www.google.co.uk = " + netUtil.getInetAddress("www.google.co.uk"));
        netUtil.DisplayNetAddress("www.google.co.uk");
        netUtil.getMyAddress();
    }
}
